version: '3.1'
services:
  stats-client:
    build: stats-service/stats-client
    image: ewm-stats-client
    container_name: stats-client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - stats-server.url=http://stats-server:9091

  stats-server:
    build: stats-service/stats-server
    image: ewm-stats-server
    container_name: stats-server
    ports:
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - STATS_SERVER_URL=http://stats-server:9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    hostname: db

  ewm-service:
    image: amazoncorretto:11-alpine-jdk
    container_name: ewm-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine

